### PR TITLE
detection: config.ru is not mandatory for a puma app

### LINKED ISSUE #78: Why does this buildpack fail detection if there is not a `config.ru` file in app source?
This [code block](https://github.com/paketo-community/puma/blob/1fd912045922f1d34c1330e559ce377e2c2d83c7/detect.go#L22-L28) here causes the buildpack to fail detection if there is no `config.ru` file in the app source. This feels like a weird requirement, should this actually cause detection to fail? We have [removed this kind of logic from buildpacks in the past](https://github.com/paketo-community/thin/pull/10) maybe we should evaluate this one as well.

### PR DESCRIPTION
**Pull request by arjun024**
The simplest puma app can be constructed using an app instance method[1]
in a `config/puma.rb`[2]. It does not require a config.ru.

1. https://www.rubydoc.info/gems/puma/Puma/DSL#app-instance_method
2. If no configuration file is specified, Puma will look for a
configuration file at `config/puma.rb`.
See https://www.rubydoc.info/gems/puma/3.6.2#configuration-file

Signed-off-by: Arjun Sreedharan <asreedharan@vmware.com>

Resolves #78

---

Please confirm the following:
* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have added an integration test, if necessary.

### CODE REVIEW

**Comment by sophiewigmore** [comment]
@arjun024 changes to detect and the new default app test look good. Why did you merge simple app test into sinatra app test? And why is the `simple_app/vendor/cache` directory still around?

**Comment by sophiewigmore** [comment]
@arjun024 can you remove the `integration/testdata/simple_app/vendor` directory please? Or move it into the sinatra app?

**Comment by arjun024** [comment]
@sophiewigmore I don't see a `integration/testdata/simple_app/vendor` directory

**Comment by sophiewigmore** [comment]
@arjun024 oops, my bad.. something got messed up on my end when I was testing out the changes.

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
